### PR TITLE
config: handle overflows of stream and flow control limits

### PR DESCRIPTION
**Pull request by marten-seemann**
This will make implementing https://github.com/libp2p/go-libp2p/issues/2290 more convenient.

### CODE REVIEW

**Comment by MarcoPolo** [comment]
How does it make it more convenient?

**Comment by MarcoPolo** [comment]
I'm generally wary of changing the config silently from the user. Although, this is being at the limits, I wouldn't expect much of a behavior change except when someone sets this to max int.

Would it be better to expose the max values that can be passed in instead?

**Comment by marten-seemann** [comment]
> Would it be better to expose the max values that can be passed in instead?

That would be an option as well. The max is `quicvarint.Max`, and we could error if the value is larger than that. Although this wouldn't surface the error when using `GetConfigForClient`.

**Comment by marten-seemann** [comment]
You have a good point that this is kind of magic behavior though. I'll add a sentence to the documentation to make it less magical.

**Pull request merged**
