### PR TITLE
Fix SendDatagram

### PR DESCRIPTION
**Pull request by nekohasekai**
SendDatagram returned wrong PeerMaxDatagramFrameSize value

### CODE REVIEW

**Comment by nekohasekai** [comment]
I found that there is already a test there

https://github.com/quic-go/quic-go/blob/7b9d21fbe6b96aa4942703df89fb93acc1ea77a9/integrationtests/self/datagram_test.go#L66.

But MatchError always returns true because DatagramTooLargeError implements Is(error)

```go
func (matcher *MatchErrorMatcher) Match(actual any) (success bool, err error) {
                ...

		// first try the built-in errors.Is
		if errors.Is(actualErr, expected.(error)) {
			return true, nil
		}
```

https://github.com/quic-go/quic-go/blob/7b9d21fbe6b96aa4942703df89fb93acc1ea77a9/errors.go#L70-L73

**Comment by nekohasekai** [comment]
It almost passed. There is a race, but it doesn't seem to be related to my changes.

**Review by marten-seemann — CHANGES_REQUESTED** [review]
I don’t understand your changes regarding the errors. I also don’t see any test that’s testing your change.

**Comment by marten-seemann** [comment]
That might be a separate issue. Please don't change the error implementation in this PR.

**Comment by marten-seemann** [comment]
@nekohasekai Are you still working on this PR? Would be nice to get the fix into the v0.43 release.

**Pull request closed without merging**
