### PR TITLE
http3: fix race condition when accessing the client's connection

### LINKED ISSUE #3694: race in http client
quic-go v0.32.0

```
2023-02-03T18:47:14.0096344Z WARNING: DATA RACE
2023-02-03T18:47:14.0096478Z Write at 0x00c0079cbbe0 by goroutine 11315:
2023-02-03T18:47:14.0096720Z   github.com/quic-go/quic-go/http3.(*client).dial()
2023-02-03T18:47:14.0097173Z       /home/runner/go/pkg/mod/github.com/quic-go/quic-go@v0.32.0/http3/client.go:114 +0x285
2023-02-03T18:47:14.0097461Z   github.com/quic-go/quic-go/http3.(*client).RoundTripOpt.func1()
2023-02-03T18:47:14.0097908Z       /home/runner/go/pkg/mod/github.com/quic-go/quic-go@v0.32.0/http3/client.go:250 +0xa4
2023-02-03T18:47:14.0098018Z   sync.(*Once).doSlow()
2023-02-03T18:47:14.0098301Z       /opt/hostedtoolcache/go/1.19.5/x64/src/sync/once.go:74 +0x101
2023-02-03T18:47:14.0098404Z   sync.(*Once).Do()
2023-02-03T18:47:14.0098675Z       /opt/hostedtoolcache/go/1.19.5/x64/src/sync/once.go:65 +0x46
2023-02-03T18:47:14.0098945Z   github.com/quic-go/quic-go/http3.(*client).RoundTripOpt()
2023-02-03T18:47:14.0099394Z       /home/runner/go/pkg/mod/github.com/quic-go/quic-go@v0.32.0/http3/client.go:249 +0x27e
2023-02-03T18:47:14.0099674Z   github.com/quic-go/quic-go/http3.(*RoundTripper).RoundTripOpt()
2023-02-03T18:47:14.0100119Z       /home/runner/go/pkg/mod/github.com/quic-go/quic-go@v0.32.0/http3/roundtrip.go:141 +0x94c
2023-02-03T18:47:14.0100389Z   github.com/quic-go/quic-go/http3.(*RoundTripper).RoundTrip()
2023-02-03T18:47:14.0100839Z       /home/runner/go/pkg/mod/github.com/quic-go/quic-go@v0.32.0/http3/roundtrip.go:155 +0x3a
2023-02-03T18:47:14.0100939Z   net/http.send()
2023-02-03T18:47:14.0101236Z       /opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:251 +0x942
2023-02-03T18:47:14.0101357Z   net/http.(*Client).send()
2023-02-03T18:47:14.0101642Z       /opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:175 +0x164
2023-02-03T18:47:14.0101753Z   net/http.(*Client).do()
2023-02-03T18:47:14.0102094Z       /opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:715 +0x10c8
2023-02-03T18:47:14.0102213Z   net/http.(*Client).Do()
2023-02-03T18:47:14.0102505Z       /opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:581 +0x549
2023-02-03T18:47:14.0110166Z
2023-02-03T18:47:14.0110315Z Previous read at 0x00c0079cbbe0 by goroutine 11321:
2023-02-03T18:47:14.0110601Z   github.com/quic-go/quic-go/http3.(*client).HandshakeComplete()
2023-02-03T18:47:14.0111050Z       /home/runner/go/pkg/mod/github.com/quic-go/quic-go@v0.32.0/http3/client.go:441 +0x3e
2023-02-03T18:47:14.0111321Z   github.com/quic-go/quic-go/http3.(*RoundTripper).getClient()
2023-02-03T18:47:14.0111779Z       /home/runner/go/pkg/mod/github.com/quic-go/quic-go@v0.32.0/http3/roundtrip.go:193 +0x662
2023-02-03T18:47:14.0112060Z   github.com/quic-go/quic-go/http3.(*RoundTripper).RoundTripOpt()
2023-02-03T18:47:14.0112516Z       /home/runner/go/pkg/mod/github.com/quic-go/quic-go@v0.32.0/http3/roundtrip.go:137 +0x924
2023-02-03T18:47:14.0112776Z   github.com/quic-go/quic-go/http3.(*RoundTripper).RoundTrip()
2023-02-03T18:47:14.0113223Z       /home/runner/go/pkg/mod/github.com/quic-go/quic-go@v0.32.0/http3/roundtrip.go:155 +0x3a
2023-02-03T18:47:14.0113325Z   net/http.send()
2023-02-03T18:47:14.0113671Z       /opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:251 +0x942
2023-02-03T18:47:14.0113795Z   net/http.(*Client).send()
2023-02-03T18:47:14.0114079Z       /opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:175 +0x164
2023-02-03T18:47:14.0114182Z   net/http.(*Client).do()
2023-02-03T18:47:14.0114477Z       /opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:715 +0x10c8
2023-02-03T18:47:14.0114589Z   net/http.(*Client).Do()
2023-02-03T18:47:14.0114882Z       /opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:581 +0x549

```

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #3694.

### CODE REVIEW

**Comment by marten-seemann** [comment]
Go 1.18 is unhappy, since `atomic.Pointer` didn't exist back then, but luckily we're about to drop support for that version anyway (#3689).

**Comment by khasanovbi** [comment]
LGTM
Could we also enable race flag in tests in CI https://github.com/quic-go/quic-go/pull/3695/commits/a28ec73811683b6a2ef3c89ff0f6c0a399d71be2 ?

**Comment by marten-seemann** [comment]
It's enabled on CircleCI: https://github.com/quic-go/quic-go/blob/5b72f4c900f209b5705bb0959399d59e495a2c6e/.circleci/config.yml#L36-L38

We should probably migrate to a single CI at some point, but for now this should be fine.

**Comment by khasanovbi** [comment]
Hi @marten-seemann
Is there any chance that this PR will be merged soon?
This is critical for us.

**Pull request merged**
