### PR TITLE
enable GSO, disable if sending fails for a particular address

### LINKED ISSUE #3911: GSO fails on some platforms / interfaces
I'm seeing a lot of `INTERNAL_ERROR (local): write udp [::]:443->[REDACTED]:42830: sendmsg: invalid argument` on the server side, causing the connection to be disconnected. They only happen when the clients are `aarch64` (raspberry pi).

Could this be related to the GSO change?

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #3911.

### CODE REVIEW

**Comment by marten-seemann** [comment]
@zllovesuki @otbutz @bt90 @kgersen Could you try out this PR, and see if it actually resolves #3911. I'll leave this PR open for a few days, and if it works, I'll ship v0.38 very soon to get GSO support out.

**Comment by zllovesuki** [comment]
@marten-seemann negative, testing with this PR in a container on raspberry pi still encounters problems

**Comment by marten-seemann** [comment]
@zllovesuki Thanks for testing! Can you provide some more details? What's the error you're getting?

**Comment by zllovesuki** [comment]
```
$ sudo k3s kubectl -n kube-system logs specter-tunnel-596bbf79cd-g9jxb
{"level":"info","ts":1690746649.3391173,"caller":"client/client.go:150","msg":"Connected to specter server","id":8319038888190,"addr":"[redacted]"}
{"level":"info","ts":1690746649.4465966,"caller":"client/client.go:366","msg":"Reusing existing client certificate","id":8319038888190,"identity":{"id":8319038888190,"token":"..."}}
{"level":"info","ts":1690746650.189319,"caller":"client/client.go:150","msg":"Connected to specter server","id":8319038888190,"addr":"[redacted]"}
{"level":"info","ts":1690746650.924124,"caller":"client/client.go:150","msg":"Connected to specter server","id":8319038888190,"addr":"[redacted]"}
{"level":"info","ts":1690746650.9242585,"caller":"client/client.go:105","msg":"Waiting for RTT measurement...","id":8319038888190,"max":3}
{"level":"info","ts":1690746652.60327,"caller":"client/client.go:465","msg":"Synchronizing tunnels in config file with specter","id":8319038888190,"tunnels":3}
{"level":"error","ts":1690746652.8073633,"caller":"client/client.go:470","msg":"Failed to query available hostnames","id":8319038888190,"error":"twirp error internal: failed to do request: Post \"https://[redacted]:443/twirp/protocol.TunnelService/RegisteredHostnames\": INTERNAL_ERROR (local): write udp [::]:54363->64.62.210.143:443: sendmsg: invalid argument","stacktrace":"kon.nect.sh/specter/tun/client.(*Client).SyncConfigTunnels\n\t/app/tun/client/client.go:470\nkon.nect.sh/specter/tun/client.(*Client).Initialize\n\t/app/tun/client/client.go:109\nkon.nect.sh/specter/cmd/client.cmdTunnel\n\t/app/cmd/client/tunnel.go:115\ngithub.com/urfave/cli/v2.(*Command).Run\n\t/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:274\ngithub.com/urfave/cli/v2.(*Command).Run\n\t/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:267\ngithub.com/urfave/cli/v2.(*Command).Run\n\t/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:267\ngithub.com/urfave/cli/v2.(*App).RunContext\n\t/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332\nmain.main\n\t/app/main.go:15\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1690746652.807639,"caller":"client/client.go:734","msg":"Listening for tunnel traffic","id":8319038888190}
{"level":"info","ts":1690746652.808922,"caller":"client/server.go:210","msg":"Local server started","id":8319038888190,"listen":"[::]:1180"}
{"level":"info","ts":1690746683.0883477,"caller":"overlay/transport.go:133","msg":"Potential connection reuse conflict, retrying to get previously cached connection","peer":{"address":"[redacted]:443"},"error":"invalid state: other peer has cached connection while we are establishing a new outgoing connection"}
{"level":"info","ts":1690746683.4750397,"caller":"overlay/transport.go:133","msg":"Potential connection reuse conflict, retrying to get previously cached connection","peer":{"address":"[redacted]:443"},"error":"invalid state: other peer has cached connection while we are establishing a new outgoing connection"}
{"level":"error","ts":1690746683.4752026,"caller":"overlay/transport.go:140","msg":"Failed to establish connection","peer":{"address":"[redacted]:443"},"error":"invalid state: other peer has cached connection while we are establishing a new outgoing connection","stacktrace":"kon.nect.sh/specter/overlay.(*QUIC).getCachedConnection\n\t/app/overlay/transport.go:140\nkon.nect.sh/specter/overlay.(*QUIC).DialStream\n\t/app/overlay/transport.go:195\nkon.nect.sh/specter/spec/rpc.getDynamicDialer.func1\n\t/app/spec/rpc/rpc.go:46\nnet/http.(*Transport).customDialTLS\n\t/usr/local/go/src/net/http/transport.go:1324\nnet/http.(*Transport).dialConn\n\t/usr/local/go/src/net/http/transport.go:1590\nnet/http.(*Transport).dialConnFor\n\t/usr/local/go/src/net/http/transport.go:1456"}
{"level":"info","ts":1690746684.1898744,"caller":"overlay/transport.go:133","msg":"Potential connection reuse conflict, retrying to get previously cached connection","peer":{"address":"[redacted]:443"},"error":"invalid state: other peer has cached connection while we are establishing a new outgoing connection"}
{"level":"info","ts":1690746684.7732158,"caller":"overlay/transport.go:133","msg":"Potential connection reuse conflict, retrying to get previously cached connection","peer":{"address":"[redacted]:443"},"error":"invalid state: other peer has cached connection while we are establishing a new outgoing connection"}
{"level":"error","ts":1690746684.7733483,"caller":"overlay/transport.go:140","msg":"Failed to establish connection","peer":{"address":"[redacted]:443"},"error":"invalid state: other peer has cached connection while we are establishing a new outgoing connection","stacktrace":"kon.nect.sh/specter/overlay.(*QUIC).getCachedConnection\n\t/app/overlay/transport.go:140\nkon.nect.sh/specter/overlay.(*QUIC).DialStream\n\t/app/overlay/transport.go:195\nkon.nect.sh/specter/spec/rpc.getDynamicDialer.func1\n\t/app/spec/rpc/rpc.go:46\nnet/http.(*Transport).customDialTLS\n\t/usr/local/go/src/net/http/transport.go:1324\nnet/http.(*Transport).dialConn\n\t/usr/local/go/src/net/http/transport.go:1590\nnet/http.(*Transport).dialConnFor\n\t/usr/local/go/src/net/http/transport.go:1456"}
{"level":"info","ts":1690746684.7735217,"caller":"client/client.go:296","msg":"Some connections have failed, opening more connections to specter server","id":8319038888190,"dead":2}
```

**Comment by zllovesuki** [comment]
The retry attempt means that it "lost" connectivity with the remotes, and initial request also failed with "Invalid Argument."

**Comment by marten-seemann** [comment]
Ok, so it looks like the GSO error detection (in `isGSOError`) doesn't trigger, since you're getting an "invalid argument" error. I'm wondering if this is because your kernel doesn't support GSO (maybe it's really old?), and we could fix that by checking for GSO support as suggested in https://github.com/quic-go/quic-go/issues/3911#issuecomment-1657249378.

**Comment by jfgiorgi** [comment]
same error as before (`sendmsg: invalid argument`).

**Comment by bt90** [comment]
(possibly?) related comment from @jwhited

https://github.com/WireGuard/wireguard-go/pull/75#issuecomment-1657250661

**Comment by marten-seemann** [comment]
What OS / kernel version are you using?

**Comment by jfgiorgi** [comment]
same as before:  see https://github.com/quic-go/quic-go/issues/3911#issuecomment-1605516136

it's an issue for IPv6 only.
These machines doesn't pass the linux kernel selftest so may be don't bother with us. 
We do use Tailscale on these configs but without IPv6 because of another reason (lack of some IPv6 routing feature) so the issue don't arise for Tailscale.

**Comment by zllovesuki** [comment]
the pi is running:
$ uname -r
6.1.21-v8+

**Comment by marten-seemann** [comment]
I added kernel GSO support detection by checking the error return value from `unix.GetsockoptInt(int(fd), unix.IPPROTO_UDP, unix.UDP_SEGMENT)`. Can you please try if that fixes the issue, @zllovesuki and @jfgiorgi?

**Comment by zllovesuki** [comment]
negative, still getting `sendmsg: invalid argument`

**Comment by marten-seemann** [comment]
I really don't know what else to do. There's not much more that we can do than checking for kernel support and the specific error.

**Comment by marten-seemann** [comment]
@zllovesuki I finally got my hands on a Raspberry Pi (Model 4) myself.

I can't reproduce the issue though. I can do QUIC downloads from QUIC servers on the internet (using the wlan0 interface), with GSO enabled on the interface. I can also transfer data from the Raspberry Pi to my computer when connected via the ethernet interface. Kernel version seems to be the same: 6.1.21-v8+.

Can you please provide more details what exactly you're running on your machine that causes this error?

**Comment by zllovesuki** [comment]
I mean, I don't know if the k3s distribution does something specific with how it starts a container. You can try running it in docker first and see if you can replicate it

**Comment by marten-seemann** [comment]
@zllovesuki What exactly should I run in Docker?

**Comment by zllovesuki** [comment]
@marten-seemann try running a docker container/k8s deployment with `miragespace/specter:gso_detection` image, with args `client tunnel -c /path/to/config.yaml`, then mount the `config.yaml` with the initial content of:
```yaml
version: 2
apex: fly.specter.im:443
tunnels:
  - target: http://127.0.0.1:8080
```

**Comment by marten-seemann** [comment]
I tried running a QUIC server inside of Docker, and doing QUIC transfers both to the Raspi and to my computer, connected via Ethernet, as well as via WiFi via Tailscale. Everything works as expected.

I'm beginning to wonder if there's anything to fix here at all. Maybe @zllovesuki's setup is just so horribly broken that we don't actually need to make any accommodations for it (other than providing a config flag to turn GSO off). Maybe we should just merge this PR as is.

@zllovesuki If you want me to continue debugging this, I will need clearer instructions from you. I have no idea how to make sense of your last message. A docker-compose file that does all the setup would be appreciated (no Kubernetes please). Please also include instructions how to exactly hit the endpoint to elicit the error message.

**Comment by zllovesuki** [comment]
@marten-seemann OK, I tried to reproduce it on bare raspberry pi, it didn't error, nor in docker, but only inside of k3s/containerd. Let's consider this to be resolved for now, and I will just turn GSO off when running in k3s.

**Comment by zllovesuki** [comment]
Can we add the environment variable back to disable GSO if needed?

**Comment by marten-seemann** [comment]
> @marten-seemann OK, I tried to reproduce it on bare raspberry pi, it didn't error, nor in docker, but only inside of k3s/containerd.

Interesting. Does it happen in a bare containerd, without k3s?

**Comment by zllovesuki** [comment]
Not sure about how to run it in just containerd. Although docker and k3s both uses containerd underneath. They must have different ways of setting up namespaces or network

**Comment by marten-seemann** [comment]
I re-added the QUIC_GO_DISABLE_GSO env.

**Review by lucas-clemente — APPROVED** [review]

**Pull request merged**
