### PR TITLE
Extend qlog support

### PR DESCRIPTION
**Pull request by birneee**
- support QLOGDIR environment variable
- support chosen_alpn qlog event
- support stream_data_moved event

Covers #4189

### CODE REVIEW

**Review by marten-seemann — COMMENTED** [review]
Can you split this up into 3 separate PRs?

1. The ALPN event totally makes sense to me.
1. What's the motivation for the stream_data_moved event? How would you use it?
1. The QLOGDIR should be optional, i.e. not be implemented in the `quic` package. Having a separate constructor in the `qlog` package makes sense to me.

**Comment by birneee** [comment]
> Can you split this up into 3 separate PRs?

I can :) 

> What's the motivation for the stream_data_moved event? How would you use it?

I would like to test/benchmark the "end-to-end"-performance that I can expect on the application layer in some scenarios. From the current qlog it is not obvious how far a stream has progressed, because of loss and reordering. For now I have a Python script that tracks the stream gaps from the qlog stream 😅

> The QLOGDIR should be optional

Not sure if I understand you correctly, you mean just a separate NewQlogDirConnectionTracer?

**Comment by marten-seemann** [comment]
> > The QLOGDIR should be optional
> 
> Not sure if I understand you correctly, you mean just a separate NewQlogDirConnectionTracer?

Yes, pretty much. Then we can tell users "If you want to record qlogs every time the QLOGDIR is set, set the `Config.Tracer` to `qlog.NewQLOGDirTracer`.

**Comment by marten-seemann** [comment]
Closing, since we've had support for the ALPN event and the QLOGDIR for a while now. Still not sure what to do about the data moved event.

**Pull request closed without merging**
