### PR TITLE
server: fix deadlock when closing concurrently with transport

### PR DESCRIPTION
**Pull request by sukunrt**
When the listener and transport are closed concurrently. We can get a deadlock

`Listener.Close` is in `Listener.CloseOnce.Do` block and calls `transport.closeServer` for `notifyOnClose`. `transport.closeServer` requires `Transport.mutex`

`Transport.Close` holds the `Transport.mutex` and calls `Listener.Close` and gets stuck at the `Listener.closeOnce.Do` block

### CODE REVIEW

**Comment by sukunrt** [comment]
Oh sorry. Yes. I didnt realise there was an open PR. Happy to close this.

**Comment by marten-seemann** [comment]
#4266 is the issue, not a PR. Please keep this one open.

**Comment by marten-seemann** [comment]
@sukunrt Did you have a way to reliably trigger this deadlock? If so, would it make sense to add this as a test case here?

**Comment by sukunrt** [comment]
On my machine this test is consistently deadlocking on master.

**Review by marten-seemann — APPROVED** [review]

**Comment by marten-seemann** [comment]
Thank you @sukunrt!

**Pull request merged**
