### PR TITLE
http3: redial for unresolved or staled connections

### PR DESCRIPTION
**Pull request by lifenjoiner**
unresolved:
Valid parameters, but handshake is not completed successfully.

staled:
A server may close the connection after requests are responsed, that stops to reuse it.

Complement #3684 (89769f40).

### CODE REVIEW

**Comment by lifenjoiner** [comment]
Unfortunately, I failed to create a google account to sign the CLA.
CLA-f

**Comment by lifenjoiner** [comment]
CLA signed.

**Comment by lifenjoiner** [comment]
The problem is about a serial requests on the same host with one http client ([dialOnce](https://github.com/quic-go/quic-go/blob/9e7fa4773ada3dffa726456f50ead9a6827c1ae7/http3/client.go#L261) with only one http3 client allowed):
1. if a request failed, the following will all fail then;
2. if a request succeeded, but the server closed the connection before a following request, then the following requests fail too.

2 `Connection %s closed` examples for case 2:
```
2023/07/13 12:28:17 client Starting new connection to dnsnl.alekberg.net (0.0.0.0:56325 -> 89.38.131.38:443), source connection ID (empty), destination connection ID 402a368ce3b7c22bd1, version v1
[2023-07-13 12:28:18] [INFO] [ams-doh-nl] TLS version: 304 - Protocol: h3 - Cipher suite: 4865
[2023-07-13 12:28:18] [NOTICE] [ams-doh-nl] OK (DoH) - rtt: 937ms
...
2023/07/13 12:28:26 client Peer closed connection with error: Application error 0x100 (remote)
2023/07/13 12:28:26 client Connection 402a368ce3b7c22bd1 closed.
```

```
2023/07/13 12:29:43 client Starting new connection to dnsse.alekberg.net (0.0.0.0:55470 -> 45.153.187.96:443), source connection ID (empty), destination connection ID a588febf56ac99eb492740141f7a2ceb9a5868, version v1
[2023-07-13 12:29:44]   127.0.0.1       github.com      A       PASS    1274ms  sth-doh-se
2023/07/13 12:29:47 client Destroying connection with error: received a stateless reset with token 562d402ae2234d37a9835b78a48d541c
2023/07/13 12:29:47 client Connection a588febf56ac99eb492740141f7a2ceb9a5868 closed.
```

**Comment by lifenjoiner** [comment]
In the scenario where a http3 client acts as a proxy.
When "[Connection %s closed](https://github.com/quic-go/quic-go/blob/de8d7a32b88688b9f85ccdab2f6e1a11bbeaa410/connection.go#L691)" happened, the `RoundTripper` should be able to initialize a new client. Or, the following requests will be refused/reset by that host.

Some servers close the connection very quickly, refer to my above examples (in seconds).
Some longer:
```
2023/07/14 12:04:24 client Starting new connection to cloudflare-dns.com ([::]:51217 -> 104.16.248.249:443), source connection ID (empty), destination connection ID ac0f77e9e1671161aeaeb34e9c, version v1
2023/07/14 12:04:24 client Queueing packet (1053 bytes) for later decryption
2023/07/14 12:09:52 client Peer closed connection with error: Application error 0x100 (remote)
2023/07/14 12:09:52 client Connection ac0f77e9e1671161aeaeb34e9c closed.
```

Must an issue be logged for each PR?

**Comment by marten-seemann** [comment]
> In the scenario where a http3 client acts as a proxy.
When "[Connection %s closed](https://github.com/quic-go/quic-go/blob/de8d7a32b88688b9f85ccdab2f6e1a11bbeaa410/connection.go#L691)" happened, the RoundTripper should be able to initialize a new client. Or, the following requests will be refused/reset by that host.

I don’t think this is accurate. You can send multiple request over the same connection, there’s no need to close it in between.

**Comment by lifenjoiner** [comment]
> there’s no need to close it in between.

Yes. But, the issue is the remote server closed the connection, as a user I can't use the client anymore.

**Comment by lifenjoiner** [comment]
Without redo handshake, extra data sent are refused.

**Comment by lifenjoiner** [comment]
Similarly, `dnsproxy` wrapped their own `http3Transport` to catch the [closed](https://github.com/AdguardTeam/dnsproxy/blob/0ac7b567367f5f2e8d90356b5439266a050e5360/upstream/upstream_doh.go#L514) status to recreate the http client.
We could make life easier here.

**Comment by marten-seemann** [comment]
Closing since this is now severely outdated. In general, please open an issue first, so we can discuss if there's any problem, and if so, how best to solve it.

**Pull request closed without merging**
